name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          # "brands" requires the domain to be merged into
          # home-assistant/brands, which is only needed for inclusion in the
          # HACS default store.
          ignore: brands

  hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
